services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.9
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    container_name: kafka
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper
  producer:
    build:
      context: ./producer
    container_name: producer
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9092
      TOPIC_NAME: transaction-topic
    ports:
      - "8081:8081"

  consumer:
    build:
      context: ./consumer
    container_name: consumer
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER: kafka:9092
      TOPIC_NAME: transaction-topic
    ports:
      - "8082:8082"
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

